name = "BlankOpenProps"
license = "MIT"
licenselink = "https://github.com/ricardoom/blank-open-props/blob/main/LICENSE"
description = "Starter Hugo theme for developers using Open Props."
homepage = "https://github.com/ricardoom/blank-open-props"
# demosite = "https://blank-demo.netlify.app/"
tags = ["starter", "development", "configurable"]
features = ["configurable theme"]
min_version = "0.20"

[author]
  name = "ricardoom"
  homepage = "https://github.com/ricardoom"

[params]
  [params.BlankOpenProps]
    normalize = "https://unpkg.com/open-props/normalize.min.css"